/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Caja-mexicana-maleta-LP-01-05.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    './models/Caja-mexicana-maleta-LP-01-05.glb'
  )
  return (
    <group {...props} dispose={null}>
      <group position={[-0.324, 0.301, 0.05]} scale={0.025}>
        <group position={[-0.079, -0.191, -0.194]}>
          <mesh
            geometry={nodes.Line104.geometry}
            material={materials['pelicula cinta']}
            position={[-4.111, 1.047, -3.736]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line105.geometry}
            material={materials['pelicula cinta']}
            position={[7.037, 1.047, -1.845]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line106.geometry}
            material={materials['pelicula cinta']}
            position={[7.119, 1.047, -3.764]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line107.geometry}
            material={materials['pelicula cinta']}
            position={[9.119, 1.047, -3.752]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line108.geometry}
            material={materials['pelicula cinta']}
            position={[3.403, 1.047, -3.71]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line109.geometry}
            material={materials['pelicula cinta']}
            position={[1.506, 1.047, -1.854]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line110.geometry}
            material={materials['pelicula cinta']}
            position={[-2.254, 1.047, -3.709]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.53, 0.53, 0.927]}
          />
          <mesh
            geometry={nodes.Line111.geometry}
            material={materials['pelicula cinta']}
            position={[5.156, 1.047, -1.876]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line112.geometry}
            material={materials['pelicula cinta']}
            position={[5.246, 1.047, -3.7]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line113.geometry}
            material={materials['pelicula cinta']}
            position={[1.525, 1.047, 0.034]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line114.geometry}
            material={materials['pelicula cinta']}
            position={[3.38, 1.047, 3.769]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.565, 0.565, 0.927]}
          />
          <mesh
            geometry={nodes.Line115.geometry}
            material={materials['pelicula cinta']}
            position={[-0.348, 1.047, 0.097]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line116.geometry}
            material={materials['pelicula cinta']}
            position={[7.081, 1.047, 1.864]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line117.geometry}
            material={materials['pelicula cinta']}
            position={[9.163, 1.047, -0.043]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line118.geometry}
            material={materials['pelicula cinta']}
            position={[5.199, 1.047, 1.833]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line119.geometry}
            material={materials['pelicula cinta']}
            position={[-2.277, 1.047, -1.838]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line120.geometry}
            material={materials['pelicula cinta']}
            position={[1.358, 1.047, 1.939]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line121.geometry}
            material={materials['pelicula cinta']}
            position={[3.358, 1.047, 1.951]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line122.geometry}
            material={materials['pelicula cinta']}
            position={[-2.358, 1.047, 1.993]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line123.geometry}
            material={materials['pelicula cinta']}
            position={[-0.439, 1.047, 1.878]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line124.geometry}
            material={materials['pelicula cinta']}
            position={[-4.506, 1.047, 0.473]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line125.geometry}
            material={materials['pelicula cinta']}
            position={[5.269, 1.047, 3.715]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line126.geometry}
            material={materials['pelicula cinta']}
            position={[-7.854, 1.047, 0.046]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line127.geometry}
            material={materials['pelicula cinta']}
            position={[-2.368, 1.047, 3.696]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line128.geometry}
            material={materials['pelicula cinta']}
            position={[-8.021, 1.047, 1.95]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line129.geometry}
            material={materials['pelicula cinta']}
            position={[-6.017, 1.047, 1.869]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line130.geometry}
            material={materials['pelicula cinta']}
            position={[-4.11, 1.047, 3.727]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line131.geometry}
            material={materials['pelicula cinta']}
            position={[8.998, 1.047, 3.814]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line132.geometry}
            material={materials['pelicula cinta']}
            position={[6.714, 1.047, 4.212]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line133.geometry}
            material={materials['pelicula cinta']}
            position={[1.448, 1.047, 3.734]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.562, 0.562, 0.927]}
          />
          <mesh
            geometry={nodes.Line134.geometry}
            material={materials['pelicula cinta']}
            position={[-7.965, 1.047, -3.814]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line135.geometry}
            material={materials['pelicula cinta']}
            position={[-7.896, 1.047, -1.88]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line136.geometry}
            material={materials['pelicula cinta']}
            position={[7.195, 1.047, -0.02]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line137.geometry}
            material={materials['pelicula cinta']}
            position={[9.033, 1.047, 1.874]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line138.geometry}
            material={materials['pelicula cinta']}
            position={[-0.758, 1.047, 3.175]}
            rotation={[Math.PI / 2, 0, -1.134]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line139.geometry}
            material={materials['pelicula cinta']}
            position={[-6.06, 1.047, 3.692]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line140.geometry}
            material={materials['pelicula cinta']}
            position={[-4.05, 1.047, 1.843]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line141.geometry}
            material={materials['pelicula cinta']}
            position={[-7.969, 1.047, 3.8]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line142.geometry}
            material={materials['pelicula cinta']}
            position={[-6.088, 1.047, -1.88]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line143.geometry}
            material={materials['pelicula cinta']}
            position={[-6.454, 1.047, 0.468]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line144.geometry}
            material={materials['pelicula cinta']}
            position={[-4.189, 1.047, -1.882]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.531, 0.531, 0.927]}
          />
          <mesh
            geometry={nodes.Line145.geometry}
            material={materials['pelicula cinta']}
            position={[-6.015, 1.047, -3.752]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line146.geometry}
            material={materials['pelicula cinta']}
            position={[3.329, 1.047, -0.021]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line147.geometry}
            material={materials['pelicula cinta']}
            position={[-2.289, 1.047, 0.06]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line148.geometry}
            material={materials['pelicula cinta']}
            position={[5.189, 1.047, -0.045]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.55, 0.55, 0.927]}
          />
          <mesh
            geometry={nodes.Line149.geometry}
            material={materials['pelicula cinta']}
            position={[8.29, 1.047, -2.297]}
            rotation={[Math.PI / 2, 0, -2.007]}
            scale={[0.55, 0.55, 0.927]}
          />
          <mesh
            geometry={nodes.Line150.geometry}
            material={materials['pelicula cinta']}
            position={[2.94, 1.047, -1.358]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line151.geometry}
            material={materials['pelicula cinta']}
            position={[1.536, 1.047, -3.81]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line152.geometry}
            material={materials['pelicula cinta']}
            position={[-0.414, 1.047, -1.843]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
        </group>
        <group position={[0.014, -1.24, -0.118]} scale={[1, 0.618, 0.848]}>
          <mesh
            geometry={nodes.Malla001.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            geometry={nodes.Malla001_1.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
        <mesh
          geometry={nodes.CajaHuecos1.geometry}
          material={materials['papel antiguo-1']}
          position={[3.741, -0.131, -0.318]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.815, 0.318, 1]}
        />
      </group>
      <group position={[0.222, 0.301, 0.049]} scale={0.025}>
        <group
          position={[0.079, -0.191, -0.175]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes.Line153.geometry}
            material={materials['pelicula cinta']}
            position={[-4.111, 1.047, -3.736]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line154.geometry}
            material={materials['pelicula cinta']}
            position={[7.037, 1.047, -1.845]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line155.geometry}
            material={materials['pelicula cinta']}
            position={[7.119, 1.047, -3.764]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line156.geometry}
            material={materials['pelicula cinta']}
            position={[9.119, 1.047, -3.752]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line157.geometry}
            material={materials['pelicula cinta']}
            position={[3.403, 1.047, -3.71]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line158.geometry}
            material={materials['pelicula cinta']}
            position={[1.506, 1.047, -1.854]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line159.geometry}
            material={materials['pelicula cinta']}
            position={[-2.254, 1.047, -3.709]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.53, 0.53, 0.927]}
          />
          <mesh
            geometry={nodes.Line160.geometry}
            material={materials['pelicula cinta']}
            position={[5.156, 1.047, -1.876]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line161.geometry}
            material={materials['pelicula cinta']}
            position={[5.246, 1.047, -3.7]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line162.geometry}
            material={materials['pelicula cinta']}
            position={[1.525, 1.047, 0.034]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line163.geometry}
            material={materials['pelicula cinta']}
            position={[3.38, 1.047, 3.769]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.565, 0.565, 0.927]}
          />
          <mesh
            geometry={nodes.Line164.geometry}
            material={materials['pelicula cinta']}
            position={[-0.348, 1.047, 0.097]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line165.geometry}
            material={materials['pelicula cinta']}
            position={[7.081, 1.047, 1.864]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line166.geometry}
            material={materials['pelicula cinta']}
            position={[9.163, 1.047, -0.043]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line167.geometry}
            material={materials['pelicula cinta']}
            position={[5.199, 1.047, 1.833]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line168.geometry}
            material={materials['pelicula cinta']}
            position={[-2.277, 1.047, -1.838]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line169.geometry}
            material={materials['pelicula cinta']}
            position={[1.358, 1.047, 1.939]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line170.geometry}
            material={materials['pelicula cinta']}
            position={[3.358, 1.047, 1.951]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line171.geometry}
            material={materials['pelicula cinta']}
            position={[-2.358, 1.047, 1.993]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line172.geometry}
            material={materials['pelicula cinta']}
            position={[-0.439, 1.047, 1.878]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line173.geometry}
            material={materials['pelicula cinta']}
            position={[-4.506, 1.047, 0.473]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line174.geometry}
            material={materials['pelicula cinta']}
            position={[5.269, 1.047, 3.715]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line175.geometry}
            material={materials['pelicula cinta']}
            position={[-7.854, 1.047, 0.046]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line176.geometry}
            material={materials['pelicula cinta']}
            position={[-2.368, 1.047, 3.696]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.516, 0.516, 0.927]}
          />
          <mesh
            geometry={nodes.Line177.geometry}
            material={materials['pelicula cinta']}
            position={[-8.021, 1.047, 1.95]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line178.geometry}
            material={materials['pelicula cinta']}
            position={[-6.017, 1.047, 1.869]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line179.geometry}
            material={materials['pelicula cinta']}
            position={[-4.11, 1.047, 3.727]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line180.geometry}
            material={materials['pelicula cinta']}
            position={[8.998, 1.047, 3.814]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line181.geometry}
            material={materials['pelicula cinta']}
            position={[6.714, 1.047, 4.212]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line182.geometry}
            material={materials['pelicula cinta']}
            position={[1.448, 1.047, 3.734]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.562, 0.562, 0.927]}
          />
          <mesh
            geometry={nodes.Line183.geometry}
            material={materials['pelicula cinta']}
            position={[-7.965, 1.047, -3.814]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line184.geometry}
            material={materials['pelicula cinta']}
            position={[-7.896, 1.047, -1.88]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line185.geometry}
            material={materials['pelicula cinta']}
            position={[7.195, 1.047, -0.02]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line186.geometry}
            material={materials['pelicula cinta']}
            position={[9.033, 1.047, 1.874]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line187.geometry}
            material={materials['pelicula cinta']}
            position={[-0.758, 1.047, 3.175]}
            rotation={[Math.PI / 2, 0, -1.134]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line188.geometry}
            material={materials['pelicula cinta']}
            position={[-6.06, 1.047, 3.692]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line189.geometry}
            material={materials['pelicula cinta']}
            position={[-4.05, 1.047, 1.843]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line190.geometry}
            material={materials['pelicula cinta']}
            position={[-7.969, 1.047, 3.8]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line191.geometry}
            material={materials['pelicula cinta']}
            position={[-6.088, 1.047, -1.88]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line192.geometry}
            material={materials['pelicula cinta']}
            position={[-6.454, 1.047, 0.468]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line193.geometry}
            material={materials['pelicula cinta']}
            position={[-4.189, 1.047, -1.882]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.531, 0.531, 0.927]}
          />
          <mesh
            geometry={nodes.Line194.geometry}
            material={materials['pelicula cinta']}
            position={[-6.015, 1.047, -3.752]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line195.geometry}
            material={materials['pelicula cinta']}
            position={[3.329, 1.047, -0.021]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line196.geometry}
            material={materials['pelicula cinta']}
            position={[-2.289, 1.047, 0.06]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
          <mesh
            geometry={nodes.Line197.geometry}
            material={materials['pelicula cinta']}
            position={[5.189, 1.047, -0.045]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.55, 0.55, 0.927]}
          />
          <mesh
            geometry={nodes.Line198.geometry}
            material={materials['pelicula cinta']}
            position={[8.29, 1.047, -2.297]}
            rotation={[Math.PI / 2, 0, -2.007]}
            scale={[0.55, 0.55, 0.927]}
          />
          <mesh
            geometry={nodes.Line199.geometry}
            material={materials['pelicula cinta']}
            position={[2.94, 1.047, -1.358]}
            rotation={[Math.PI / 2, 0, 1.309]}
            scale={[0.582, 0.582, 0.927]}
          />
          <mesh
            geometry={nodes.Line200.geometry}
            material={materials['pelicula cinta']}
            position={[1.536, 1.047, -3.81]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.607, 0.607, 0.927]}
          />
          <mesh
            geometry={nodes.Line201.geometry}
            material={materials['pelicula cinta']}
            position={[-0.414, 1.047, -1.843]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.557, 0.557, 0.927]}
          />
        </group>
        <group
          position={[-0.014, -1.24, -0.118]}
          rotation={[Math.PI, 0, 0]}
          scale={[-1, -0.618, -0.848]}
        >
          <mesh
            geometry={nodes.Malla051.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            geometry={nodes.Malla051_1.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
        <mesh
          geometry={nodes.CajaHuecos002.geometry}
          material={materials['papel antiguo-1']}
          position={[-3.741, -0.131, -0.051]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.815, 0.318, 1]}
        />
      </group>
      <group position={[-0.049, 0.124, 0]} scale={0.025}>
        <group position={[0.031, 2.601, -11.753]}>
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials['metal-1']}
            position={[-13.657, 0.733, -0.03]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[2.481, 1.774, 2.481]}
          />
        </group>
        <group position={[0.164, 2.398, 11.1]}>
          <group
            position={[22.347, -2.723, -11.08]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 0.557, 1]}
          >
            <mesh
              geometry={nodes.Malla166.geometry}
              material={materials['metal-3']}
            />
            <mesh
              geometry={nodes.Malla166_1.geometry}
              material={materials['metal-2']}
            />
            <mesh
              geometry={nodes.Malla166_2.geometry}
              material={materials['metal-cuero-1']}
            />
            <mesh
              geometry={nodes.Malla166_3.geometry}
              material={materials['cuero maleta-2+']}
            />
            <mesh
              geometry={nodes.Malla166_4.geometry}
              material={materials['cuero maleta-2']}
            />
            <mesh
              geometry={nodes.Malla166_5.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              geometry={nodes.Malla166_6.geometry}
              material={materials['tela interior-1']}
            />
            <mesh
              geometry={nodes.Malla166_7.geometry}
              material={materials.mango}
            />
          </group>
        </group>
        <group position={[0, 3.842, -0.185]}>
          <group
            position={[14.441, -0.522, -11.636]}
            scale={[1.428, 1.412, 1.428]}
          >
            <mesh
              geometry={nodes.Malla111.geometry}
              material={materials['metal-3']}
            />
            <mesh
              geometry={nodes.Malla111_1.geometry}
              material={materials['metal-cuero-1']}
            />
            <mesh
              geometry={nodes.Malla111_2.geometry}
              material={materials['cuero maleta-1']}
            />
            <mesh
              geometry={nodes.Malla111_3.geometry}
              material={materials['metal-2']}
            />
            <mesh
              geometry={nodes.Malla111_4.geometry}
              material={materials['metal-1']}
            />
          </group>
        </group>
      </group>
      <group
        position={[-0.324, 0.429, -0.162]}
        rotation={[-2.269, 0, 0]}
        scale={[0.025, 0.016, 0.022]}
      >
        <mesh
          geometry={nodes.Malla174.geometry}
          material={materials['cuero marron-1']}
        />
        <mesh
          geometry={nodes.Malla174_1.geometry}
          material={materials[' cuadricula interior']}
        />
        <mesh
          geometry={nodes.Malla174_2.geometry}
          material={materials['papel antiguo-1']}
        />
      </group>
      <group
        position={[0.222, 0.429, -0.163]}
        rotation={[-2.269, 0, 0]}
        scale={[0.025, 0.016, 0.022]}
      >
        <mesh
          geometry={nodes.Malla175.geometry}
          material={materials['cuero marron-1']}
        />
        <mesh
          geometry={nodes.Malla175_1.geometry}
          material={materials[' cuadricula interior']}
        />
        <mesh
          geometry={nodes.Malla175_2.geometry}
          material={materials['papel antiguo-1']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Caja-mexicana-maleta-LP-01-05.glb')
