/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Caja-mexicana-maleta-LP-01-ani.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    './models/Caja-mexicana-maleta-LP-01-ani.glb'
  )
  const { actions } = useAnimations(animations, group)

  console.log(actions)
  useEffect(() => {
    actions['Caj12Base|Take 001|BaseLayer'].play()
    actions['Caja1Tapa|Take 001|BaseLayer'].play()
    actions['Caja2Base|Take 001|BaseLayer'].play()
    actions['Caja2Tapa|Take 001|BaseLayer'].play()
    actions['MaletaTapa|Take 001|BaseLayer'].play()
    actions['Tape001|Take 001|BaseLayer'].play()
    actions['Tape002|Take 001|BaseLayer'].play()
    actions['Tape003|Take 001|BaseLayer'].play()
    actions['Tape004|Take 001|BaseLayer'].play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group
          name='Tape001'
          position={[0.358, -0.001, -0.138]}
          rotation={[Math.PI / 2, -1.558, -Math.PI / 2]}
          scale={0.025}
        />
        <group
          name='Tape001Target'
          position={[0.357, 0.059, -0.138]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape002'
          position={[0.307, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.025}
        />
        <group
          name='Tape002Target'
          position={[-0.195, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape003'
          position={[0.343, -0.013, -0.094]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape003Target'
          position={[0.343, -0.013, 0.207]}
          scale={0.025}
        />
        <group
          name='Tape004'
          position={[0.327, 0, -0.093]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape004Target'
          position={[0.327, 0, 0.158]}
          scale={0.025}
        />
        <group
          name='MaletaCuerpoMango'
          position={[-0.047, 0.01, -0.009]}
          scale={0.025}
        >
          <mesh
            name='Malla'
            geometry={nodes.Malla.geometry}
            material={materials['cuero maleta-2']}
          />
          <mesh
            name='Malla_1'
            geometry={nodes.Malla_1.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            name='Malla_2'
            geometry={nodes.Malla_2.geometry}
            material={materials['tela interior-1']}
          />
          <mesh
            name='Malla_3'
            geometry={nodes.Malla_3.geometry}
            material={materials['metal-cuero-1']}
          />
          <mesh
            name='Malla_4'
            geometry={nodes.Malla_4.geometry}
            material={materials['cuero maleta-2+']}
          />
          <mesh
            name='Malla_5'
            geometry={nodes.Malla_5.geometry}
            material={materials['metal-2']}
          />
          <mesh
            name='Malla_6'
            geometry={nodes.Malla_6.geometry}
            material={materials['metal-3']}
          />
          <mesh
            name='Malla_7'
            geometry={nodes.Malla_7.geometry}
            material={materials['metal-1']}
          />
          <mesh
            name='Malla_8'
            geometry={nodes.Malla_8.geometry}
            material={materials.mango}
          />
        </group>
        <group
          name='MaletaTapa'
          position={[-0.047, 0.01, -0.009]}
          scale={0.025}
        >
          <mesh
            name='Malla001'
            geometry={nodes.Malla001.geometry}
            material={materials['cuero maleta-1']}
          />
          <mesh
            name='Malla001_1'
            geometry={nodes.Malla001_1.geometry}
            material={materials['metal-3']}
          />
          <mesh
            name='Malla001_2'
            geometry={nodes.Malla001_2.geometry}
            material={materials['metal-cuero-1']}
          />
          <mesh
            name='Malla001_3'
            geometry={nodes.Malla001_3.geometry}
            material={materials['metal-2']}
          />
        </group>
        <group
          name='Caj12Base'
          position={[-0.531, 0.089, -0.105]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.015, 0.015, 0.024]}
        >
          <mesh
            name='Malla002'
            geometry={nodes.Malla002.geometry}
            material={materials['pelicula cinta']}
          />
          <mesh
            name='Malla002_1'
            geometry={nodes.Malla002_1.geometry}
            material={materials['papel antiguo-1']}
          />
          <mesh
            name='Malla002_2'
            geometry={nodes.Malla002_2.geometry}
            material={materials['cuero marron-1']}
          />
        </group>
        <group
          name='Caja2Base'
          position={[-0.002, 0.089, -0.106]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={[0.015, 0.015, 0.024]}
        >
          <mesh
            name='Malla003'
            geometry={nodes.Malla003.geometry}
            material={materials['pelicula cinta']}
          />
          <mesh
            name='Malla003_1'
            geometry={nodes.Malla003_1.geometry}
            material={materials['papel antiguo-1']}
          />
          <mesh
            name='Malla003_2'
            geometry={nodes.Malla003_2.geometry}
            material={materials['cuero marron-1']}
          />
        </group>
        <group
          name='Caja1Tapa'
          position={[-0.326, 0.095, -0.005]}
          scale={[0.025, 0.016, 0.022]}
        >
          <mesh
            name='Malla004'
            geometry={nodes.Malla004.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            name='Malla004_1'
            geometry={nodes.Malla004_1.geometry}
            material={materials[' cuadricula interior']}
          />
          <mesh
            name='Malla004_2'
            geometry={nodes.Malla004_2.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
        <group
          name='Caja2Tapa'
          position={[0.23, 0.095, -0.006]}
          scale={[0.025, 0.016, 0.022]}
        >
          <mesh
            name='Malla005'
            geometry={nodes.Malla005.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            name='Malla005_1'
            geometry={nodes.Malla005_1.geometry}
            material={materials[' cuadricula interior']}
          />
          <mesh
            name='Malla005_2'
            geometry={nodes.Malla005_2.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Caja-mexicana-maleta-LP-01-ani.glb')
