/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Caja-mexicana-maleta-LP-05-ani.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    './models/Caja-mexicana-maleta-LP-05-ani.glb'
  )
  const { actions } = useAnimations(animations, group)

  console.log(actions)
  useEffect(() => {
    actions['Caja1BaseAction'].play()
    actions['Caja1TapaAction'].play()
    actions['Caja2BaseAction'].play()
    actions['Caja2TapaAction'].play()
    actions['MaletaBordeTapaAction'].play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group
          name='Tape001'
          position={[0.358, -0.001, -0.138]}
          rotation={[1.571, -1.558, -1.571]}
          scale={0.025}
        />
        <group
          name='Tape001Target'
          position={[0.357, 0.059, -0.138]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape002'
          position={[0.307, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.025}
        />
        <group
          name='Tape002Target'
          position={[-0.195, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape003'
          position={[0.343, -0.013, -0.094]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape003Target'
          position={[0.343, -0.013, 0.207]}
          scale={0.025}
        />
        <group
          name='Tape004'
          position={[0.327, 0, -0.093]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape004Target'
          position={[0.327, 0, 0.158]}
          scale={0.025}
        />
        <group name='Caja1Base' position={[-0.324, 0.037, 0.05]} scale={0.025}>
          <group name='CajaCarretes1' position={[-0.079, -0.191, -0.194]} />
          <group
            name='CajaBase1'
            position={[0.014, -1.24, -3.081]}
            scale={[1, 0.618, 0.848]}
          >
            <mesh
              name='Malla001'
              geometry={nodes.Malla001.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla001_1'
              geometry={nodes.Malla001_1.geometry}
              material={materials['papel antiguo-1']}
            />
            <mesh
              name='Malla001_2'
              geometry={nodes.Malla001_2.geometry}
              material={materials['pelicula cinta']}
            />
          </group>
        </group>
        <group name='Caja2Base' position={[0.222, 0.037, 0.049]} scale={0.025}>
          <group
            name='CajaCarretes002'
            position={[0.079, -0.191, -0.175]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <group
            name='CajaBase002'
            position={[-0.014, -1.24, -3.081]}
            rotation={[Math.PI, 0, 0]}
            scale={[-1, -0.618, -0.848]}
          >
            <mesh
              name='Malla051'
              geometry={nodes.Malla051.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla051_1'
              geometry={nodes.Malla051_1.geometry}
              material={materials['papel antiguo-1']}
            />
            <mesh
              name='Malla051_2'
              geometry={nodes.Malla051_2.geometry}
              material={materials['pelicula cinta']}
            />
          </group>
        </group>
        <group
          name='MaletaCuerpoMango'
          position={[-0.049, 0.124, 0]}
          scale={0.025}
        >
          <group name='BisagrasEje' position={[0.031, 2.601, -11.753]}>
            <mesh
              name='Cylinder019'
              geometry={nodes.Cylinder019.geometry}
              material={materials['metal-1']}
              position={[-13.657, 0.733, -0.03]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[2.481, 1.774, 2.481]}
            />
          </group>
          <group name='Cierre1' position={[-13.095, 2.24, 11.097]} />
          <group name='Cierre2' position={[13.244, 2.24, 11.097]} />
          <group name='CierreCentral' position={[0.164, 2.398, 11.1]}>
            <group
              name='Sphere051'
              position={[22.347, -2.723, -11.08]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.557, 1]}
            >
              <mesh
                name='Malla166'
                geometry={nodes.Malla166.geometry}
                material={materials['metal-3']}
              />
              <mesh
                name='Malla166_1'
                geometry={nodes.Malla166_1.geometry}
                material={materials['metal-2']}
              />
              <mesh
                name='Malla166_2'
                geometry={nodes.Malla166_2.geometry}
                material={materials['metal-cuero-1']}
              />
              <mesh
                name='Malla166_3'
                geometry={nodes.Malla166_3.geometry}
                material={materials['cuero maleta-2+']}
              />
              <mesh
                name='Malla166_4'
                geometry={nodes.Malla166_4.geometry}
                material={materials['cuero maleta-2']}
              />
              <mesh
                name='Malla166_5'
                geometry={nodes.Malla166_5.geometry}
                material={materials['cuero marron-1']}
              />
              <mesh
                name='Malla166_6'
                geometry={nodes.Malla166_6.geometry}
                material={materials['tela interior-1']}
              />
              <mesh
                name='Malla166_7'
                geometry={nodes.Malla166_7.geometry}
                material={materials.mango}
              />
            </group>
          </group>
          <group
            name='MaletaEsquinasCuerpo'
            position={[0.031, -1.329, -0.348]}
          />
          <group name='MaletaTapa' position={[0, 3.842, -0.185]}>
            <group name='Bisagras' position={[0.031, 0.329, -11.577]} />
            <group
              name='CierreCentralGancho'
              position={[0.201, -0.516, 11.449]}
            />
            <group name='CierreGancho1' position={[-13.135, -0.298, 11.313]} />
            <group name='CierreGancho2' position={[13.204, -0.298, 11.313]} />
            <group name='Group001' position={[-21.452, 0.681, 10.041]} />
            <group name='Group002' position={[-21.377, 0.681, -10.36]} />
            <group name='Group003' position={[21.423, 0.681, -10.361]} />
            <group name='Group004' position={[21.439, 0.681, 10.041]} />
            <group
              name='MaletaBordeTapa'
              position={[14.441, -0.522, -11.636]}
              scale={[1.428, 1.412, 1.428]}
            >
              <mesh
                name='Malla111'
                geometry={nodes.Malla111.geometry}
                material={materials['metal-3']}
              />
              <mesh
                name='Malla111_1'
                geometry={nodes.Malla111_1.geometry}
                material={materials['metal-cuero-1']}
              />
              <mesh
                name='Malla111_2'
                geometry={nodes.Malla111_2.geometry}
                material={materials['cuero maleta-1']}
              />
              <mesh
                name='Malla111_3'
                geometry={nodes.Malla111_3.geometry}
                material={materials['metal-2']}
              />
              <mesh
                name='Malla111_4'
                geometry={nodes.Malla111_4.geometry}
                material={materials['metal-1']}
              />
            </group>
          </group>
          <group name='Mangobase' position={[0.202, 0.861, 11.327]} />
        </group>
        <group
          name='Caja1Tapa'
          position={[0.468, 0.065, -0.157]}
          rotation={[-0.016, 0, 0]}
          scale={[0.025, 0.016, 0.022]}
        >
          <mesh
            name='Malla174'
            geometry={nodes.Malla174.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            name='Malla174_1'
            geometry={nodes.Malla174_1.geometry}
            material={materials[' cuadricula interior']}
          />
          <mesh
            name='Malla174_2'
            geometry={nodes.Malla174_2.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
        <group
          name='Caja2Tapa'
          position={[0.468, 0.065, -0.157]}
          rotation={[-0.01, 0, 0]}
          scale={[0.025, 0.016, 0.022]}
        >
          <mesh
            name='Malla175'
            geometry={nodes.Malla175.geometry}
            material={materials['cuero marron-1']}
          />
          <mesh
            name='Malla175_1'
            geometry={nodes.Malla175_1.geometry}
            material={materials[' cuadricula interior']}
          />
          <mesh
            name='Malla175_2'
            geometry={nodes.Malla175_2.geometry}
            material={materials['papel antiguo-1']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Caja-mexicana-maleta-LP-05-ani.glb')
