/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/Caja-mexicana-maleta-01.glb -s 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/Caja-mexicana-maleta-01.glb')
  //const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group
          name='Tape001'
          position={[0.358, -0.001, -0.138]}
          rotation={[Math.PI / 2, -1.558, -Math.PI / 2]}
          scale={0.025}
        />
        <group
          name='Tape001Target'
          position={[0.357, 0.059, -0.138]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape002'
          position={[0.307, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.025}
        />
        <group
          name='Tape002Target'
          position={[-0.195, -0.014, -0.144]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.025}
        />
        <group
          name='Tape003'
          position={[0.343, -0.013, -0.094]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape003Target'
          position={[0.343, -0.013, 0.207]}
          scale={0.025}
        />
        <group
          name='Tape004'
          position={[0.327, 0, -0.093]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.025}
        />
        <group
          name='Tape004Target'
          position={[0.327, 0, 0.158]}
          scale={0.025}
        />
        <group
          name='Caja1'
          position={[-0.438, 0.4, -0.088]}
          rotation={[0, 0.698, 0]}
          scale={0.025}
        >
          <group name='CajaCarretes1' position={[-0.058, -2.911, 4.099]}>
            <mesh
              name='Line001'
              castShadow
              receiveShadow
              geometry={nodes.Line001.geometry}
              material={materials['pelicula cinta']}
              position={[-4.108, 1.047, -3.736]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line002'
              castShadow
              receiveShadow
              geometry={nodes.Line002.geometry}
              material={materials['pelicula cinta']}
              position={[7.04, 1.047, -1.845]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line003'
              castShadow
              receiveShadow
              geometry={nodes.Line003.geometry}
              material={materials['pelicula cinta']}
              position={[7.122, 1.047, -3.764]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line004'
              castShadow
              receiveShadow
              geometry={nodes.Line004.geometry}
              material={materials['pelicula cinta']}
              position={[9.122, 1.047, -3.752]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line005'
              castShadow
              receiveShadow
              geometry={nodes.Line005.geometry}
              material={materials['pelicula cinta']}
              position={[3.406, 1.047, -3.71]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line006'
              castShadow
              receiveShadow
              geometry={nodes.Line006.geometry}
              material={materials['pelicula cinta']}
              position={[1.509, 1.047, -1.854]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line007'
              castShadow
              receiveShadow
              geometry={nodes.Line007.geometry}
              material={materials['pelicula cinta']}
              position={[-2.251, 1.047, -3.709]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.53, 0.53, 0.927]}
            />
            <mesh
              name='Line008'
              castShadow
              receiveShadow
              geometry={nodes.Line008.geometry}
              material={materials['pelicula cinta']}
              position={[5.159, 1.047, -1.876]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.516, 0.516, 0.927]}
            />
            <mesh
              name='Line009'
              castShadow
              receiveShadow
              geometry={nodes.Line009.geometry}
              material={materials['pelicula cinta']}
              position={[5.249, 1.047, -3.7]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line010'
              castShadow
              receiveShadow
              geometry={nodes.Line010.geometry}
              material={materials['pelicula cinta']}
              position={[1.528, 1.047, 0.034]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line011'
              castShadow
              receiveShadow
              geometry={nodes.Line011.geometry}
              material={materials['pelicula cinta']}
              position={[3.383, 1.047, 3.769]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.565, 0.565, 0.927]}
            />
            <mesh
              name='Line012'
              castShadow
              receiveShadow
              geometry={nodes.Line012.geometry}
              material={materials['pelicula cinta']}
              position={[-0.345, 1.047, 0.097]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line013'
              castShadow
              receiveShadow
              geometry={nodes.Line013.geometry}
              material={materials['pelicula cinta']}
              position={[7.084, 1.047, 1.864]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line014'
              castShadow
              receiveShadow
              geometry={nodes.Line014.geometry}
              material={materials['pelicula cinta']}
              position={[9.166, 1.047, -0.043]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line015'
              castShadow
              receiveShadow
              geometry={nodes.Line015.geometry}
              material={materials['pelicula cinta']}
              position={[5.202, 1.047, 1.833]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.516, 0.516, 0.927]}
            />
            <mesh
              name='Line016'
              castShadow
              receiveShadow
              geometry={nodes.Line016.geometry}
              material={materials['pelicula cinta']}
              position={[-2.274, 1.047, -1.838]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line017'
              castShadow
              receiveShadow
              geometry={nodes.Line017.geometry}
              material={materials['pelicula cinta']}
              position={[1.361, 1.047, 1.939]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line018'
              castShadow
              receiveShadow
              geometry={nodes.Line018.geometry}
              material={materials['pelicula cinta']}
              position={[3.361, 1.047, 1.951]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line019'
              castShadow
              receiveShadow
              geometry={nodes.Line019.geometry}
              material={materials['pelicula cinta']}
              position={[-2.355, 1.047, 1.993]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line020'
              castShadow
              receiveShadow
              geometry={nodes.Line020.geometry}
              material={materials['pelicula cinta']}
              position={[-0.436, 1.047, 1.878]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line021'
              castShadow
              receiveShadow
              geometry={nodes.Line021.geometry}
              material={materials['pelicula cinta']}
              position={[-4.503, 1.047, 0.473]}
              rotation={[Math.PI / 2, 0, 1.309]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line022'
              castShadow
              receiveShadow
              geometry={nodes.Line022.geometry}
              material={materials['pelicula cinta']}
              position={[5.272, 1.047, 3.715]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line023'
              castShadow
              receiveShadow
              geometry={nodes.Line023.geometry}
              material={materials['pelicula cinta']}
              position={[-7.851, 1.047, 0.046]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line024'
              castShadow
              receiveShadow
              geometry={nodes.Line024.geometry}
              material={materials['pelicula cinta']}
              position={[-2.365, 1.047, 3.696]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.516, 0.516, 0.927]}
            />
            <mesh
              name='Line025'
              castShadow
              receiveShadow
              geometry={nodes.Line025.geometry}
              material={materials['pelicula cinta']}
              position={[-8.018, 1.047, 1.95]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line026'
              castShadow
              receiveShadow
              geometry={nodes.Line026.geometry}
              material={materials['pelicula cinta']}
              position={[-6.014, 1.047, 1.869]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line027'
              castShadow
              receiveShadow
              geometry={nodes.Line027.geometry}
              material={materials['pelicula cinta']}
              position={[-4.107, 1.047, 3.727]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line028'
              castShadow
              receiveShadow
              geometry={nodes.Line028.geometry}
              material={materials['pelicula cinta']}
              position={[9.001, 1.047, 3.814]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line029'
              castShadow
              receiveShadow
              geometry={nodes.Line029.geometry}
              material={materials['pelicula cinta']}
              position={[6.717, 1.047, 4.212]}
              rotation={[Math.PI / 2, 0, 1.309]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line030'
              castShadow
              receiveShadow
              geometry={nodes.Line030.geometry}
              material={materials['pelicula cinta']}
              position={[1.451, 1.047, 3.734]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.562, 0.562, 0.927]}
            />
            <mesh
              name='Line031'
              castShadow
              receiveShadow
              geometry={nodes.Line031.geometry}
              material={materials['pelicula cinta']}
              position={[-7.962, 1.047, -3.814]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line032'
              castShadow
              receiveShadow
              geometry={nodes.Line032.geometry}
              material={materials['pelicula cinta']}
              position={[-7.893, 1.047, -1.88]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line033'
              castShadow
              receiveShadow
              geometry={nodes.Line033.geometry}
              material={materials['pelicula cinta']}
              position={[7.198, 1.047, -0.02]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line034'
              castShadow
              receiveShadow
              geometry={nodes.Line034.geometry}
              material={materials['pelicula cinta']}
              position={[9.036, 1.047, 1.874]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line035'
              castShadow
              receiveShadow
              geometry={nodes.Line035.geometry}
              material={materials['pelicula cinta']}
              position={[-0.755, 1.047, 3.175]}
              rotation={[Math.PI / 2, 0, -1.134]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line036'
              castShadow
              receiveShadow
              geometry={nodes.Line036.geometry}
              material={materials['pelicula cinta']}
              position={[-6.057, 1.047, 3.692]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line037'
              castShadow
              receiveShadow
              geometry={nodes.Line037.geometry}
              material={materials['pelicula cinta']}
              position={[-4.047, 1.047, 1.843]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line038'
              castShadow
              receiveShadow
              geometry={nodes.Line038.geometry}
              material={materials['pelicula cinta']}
              position={[-7.966, 1.047, 3.8]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line039'
              castShadow
              receiveShadow
              geometry={nodes.Line039.geometry}
              material={materials['pelicula cinta']}
              position={[-6.085, 1.047, -1.88]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line040'
              castShadow
              receiveShadow
              geometry={nodes.Line040.geometry}
              material={materials['pelicula cinta']}
              position={[-6.451, 1.047, 0.468]}
              rotation={[Math.PI / 2, 0, 1.309]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line041'
              castShadow
              receiveShadow
              geometry={nodes.Line041.geometry}
              material={materials['pelicula cinta']}
              position={[-4.186, 1.047, -1.882]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.531, 0.531, 0.927]}
            />
            <mesh
              name='Line042'
              castShadow
              receiveShadow
              geometry={nodes.Line042.geometry}
              material={materials['pelicula cinta']}
              position={[-6.012, 1.047, -3.752]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line043'
              castShadow
              receiveShadow
              geometry={nodes.Line043.geometry}
              material={materials['pelicula cinta']}
              position={[3.332, 1.047, -0.021]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line044'
              castShadow
              receiveShadow
              geometry={nodes.Line044.geometry}
              material={materials['pelicula cinta']}
              position={[-2.286, 1.047, 0.06]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
            <mesh
              name='Line045'
              castShadow
              receiveShadow
              geometry={nodes.Line045.geometry}
              material={materials['pelicula cinta']}
              position={[5.192, 1.047, -0.045]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.55, 0.55, 0.927]}
            />
            <mesh
              name='Line046'
              castShadow
              receiveShadow
              geometry={nodes.Line046.geometry}
              material={materials['pelicula cinta']}
              position={[8.293, 1.047, -2.297]}
              rotation={[Math.PI / 2, 0, -2.007]}
              scale={[0.55, 0.55, 0.927]}
            />
            <mesh
              name='Line047'
              castShadow
              receiveShadow
              geometry={nodes.Line047.geometry}
              material={materials['pelicula cinta']}
              position={[2.943, 1.047, -1.358]}
              rotation={[Math.PI / 2, 0, 1.309]}
              scale={[0.582, 0.582, 0.927]}
            />
            <mesh
              name='Line048'
              castShadow
              receiveShadow
              geometry={nodes.Line048.geometry}
              material={materials['pelicula cinta']}
              position={[1.539, 1.047, -3.81]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.607, 0.607, 0.927]}
            />
            <mesh
              name='Line049'
              castShadow
              receiveShadow
              geometry={nodes.Line049.geometry}
              material={materials['pelicula cinta']}
              position={[-0.411, 1.047, -1.843]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.557, 0.557, 0.927]}
            />
          </group>
          <group
            name='CajaBase1'
            position={[0.017, -3.959, 4.174]}
            scale={[1, 0.618, 0.848]}
          >
            <mesh
              name='Malla001'
              castShadow
              receiveShadow
              geometry={nodes.Malla001.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla001_1'
              castShadow
              receiveShadow
              geometry={nodes.Malla001_1.geometry}
              material={materials['papel antiguo-1']}
            />
          </group>
          <mesh
            name='CajaHuecos1'
            castShadow
            receiveShadow
            geometry={nodes.CajaHuecos1.geometry}
            material={materials['papel antiguo-1']}
            position={[3.744, -2.851, 3.975]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.815, 0.318, 1]}
          />
          <group
            name='CajaTapa1'
            position={[0.017, 0.86, -5.04]}
            rotation={[-2.618, 0, 0]}
            scale={[1, 0.618, 0.848]}
          >
            <mesh
              name='Malla'
              castShadow
              receiveShadow
              geometry={nodes.Malla.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla_1'
              castShadow
              receiveShadow
              geometry={nodes.Malla_1.geometry}
              material={materials[' cuadricula interior']}
            />
            <mesh
              name='Malla_2'
              castShadow
              receiveShadow
              geometry={nodes.Malla_2.geometry}
              material={materials['papel antiguo-1']}
            />
          </group>
        </group>
        <group name='Caja2' position={[0.289, 0.397, -0.097]} scale={0.025}>
          <group
            name='CajaCarretes2'
            position={[-2.193, -2.56, 3.705]}
            rotation={[0, -Math.PI / 6, 0]}
          >
            <mesh
              name='Line050'
              castShadow
              receiveShadow
              geometry={nodes.Line050.geometry}
              material={materials['pelicula cinta']}
              position={[-4.108, 1.047, 3.736]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line051'
              castShadow
              receiveShadow
              geometry={nodes.Line051.geometry}
              material={materials['pelicula cinta']}
              position={[7.04, 1.047, 1.845]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line052'
              castShadow
              receiveShadow
              geometry={nodes.Line052.geometry}
              material={materials['pelicula cinta']}
              position={[7.122, 1.047, 3.764]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line053'
              castShadow
              receiveShadow
              geometry={nodes.Line053.geometry}
              material={materials['pelicula cinta']}
              position={[9.122, 1.047, 3.752]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line054'
              castShadow
              receiveShadow
              geometry={nodes.Line054.geometry}
              material={materials['pelicula cinta']}
              position={[3.406, 1.047, 3.71]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line055'
              castShadow
              receiveShadow
              geometry={nodes.Line055.geometry}
              material={materials['pelicula cinta']}
              position={[1.509, 1.047, 1.854]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line056'
              castShadow
              receiveShadow
              geometry={nodes.Line056.geometry}
              material={materials['pelicula cinta']}
              position={[-2.251, 1.047, 3.709]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.53, -0.53, -0.927]}
            />
            <mesh
              name='Line057'
              castShadow
              receiveShadow
              geometry={nodes.Line057.geometry}
              material={materials['pelicula cinta']}
              position={[5.159, 1.047, 1.876]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.516, -0.516, -0.927]}
            />
            <mesh
              name='Line058'
              castShadow
              receiveShadow
              geometry={nodes.Line058.geometry}
              material={materials['pelicula cinta']}
              position={[5.249, 1.047, 3.7]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line059'
              castShadow
              receiveShadow
              geometry={nodes.Line059.geometry}
              material={materials['pelicula cinta']}
              position={[1.528, 1.047, -0.034]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line060'
              castShadow
              receiveShadow
              geometry={nodes.Line060.geometry}
              material={materials['pelicula cinta']}
              position={[3.383, 1.047, -3.769]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.565, -0.565, -0.927]}
            />
            <mesh
              name='Line061'
              castShadow
              receiveShadow
              geometry={nodes.Line061.geometry}
              material={materials['pelicula cinta']}
              position={[-0.345, 1.047, -0.097]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line062'
              castShadow
              receiveShadow
              geometry={nodes.Line062.geometry}
              material={materials['pelicula cinta']}
              position={[7.084, 1.047, -1.864]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line063'
              castShadow
              receiveShadow
              geometry={nodes.Line063.geometry}
              material={materials['pelicula cinta']}
              position={[9.166, 1.047, 0.043]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line064'
              castShadow
              receiveShadow
              geometry={nodes.Line064.geometry}
              material={materials['pelicula cinta']}
              position={[5.202, 1.047, -1.833]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.516, -0.516, -0.927]}
            />
            <mesh
              name='Line065'
              castShadow
              receiveShadow
              geometry={nodes.Line065.geometry}
              material={materials['pelicula cinta']}
              position={[-2.274, 1.047, 1.838]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line066'
              castShadow
              receiveShadow
              geometry={nodes.Line066.geometry}
              material={materials['pelicula cinta']}
              position={[1.361, 1.047, -1.939]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line067'
              castShadow
              receiveShadow
              geometry={nodes.Line067.geometry}
              material={materials['pelicula cinta']}
              position={[3.361, 1.047, -1.951]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line068'
              castShadow
              receiveShadow
              geometry={nodes.Line068.geometry}
              material={materials['pelicula cinta']}
              position={[-2.355, 1.047, -1.993]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line069'
              castShadow
              receiveShadow
              geometry={nodes.Line069.geometry}
              material={materials['pelicula cinta']}
              position={[-0.436, 1.047, -1.878]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line070'
              castShadow
              receiveShadow
              geometry={nodes.Line070.geometry}
              material={materials['pelicula cinta']}
              position={[-4.503, 1.047, -0.473]}
              rotation={[-Math.PI / 2, 0, -1.833]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line071'
              castShadow
              receiveShadow
              geometry={nodes.Line071.geometry}
              material={materials['pelicula cinta']}
              position={[5.272, 1.047, -3.715]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line072'
              castShadow
              receiveShadow
              geometry={nodes.Line072.geometry}
              material={materials['pelicula cinta']}
              position={[-7.851, 1.047, -0.046]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line073'
              castShadow
              receiveShadow
              geometry={nodes.Line073.geometry}
              material={materials['pelicula cinta']}
              position={[-2.365, 1.047, -3.696]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.516, -0.516, -0.927]}
            />
            <mesh
              name='Line074'
              castShadow
              receiveShadow
              geometry={nodes.Line074.geometry}
              material={materials['pelicula cinta']}
              position={[-8.018, 1.047, -1.95]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line075'
              castShadow
              receiveShadow
              geometry={nodes.Line075.geometry}
              material={materials['pelicula cinta']}
              position={[-6.014, 1.047, -1.869]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line076'
              castShadow
              receiveShadow
              geometry={nodes.Line076.geometry}
              material={materials['pelicula cinta']}
              position={[-4.107, 1.047, -3.727]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line077'
              castShadow
              receiveShadow
              geometry={nodes.Line077.geometry}
              material={materials['pelicula cinta']}
              position={[9.001, 1.047, -3.814]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line078'
              castShadow
              receiveShadow
              geometry={nodes.Line078.geometry}
              material={materials['pelicula cinta']}
              position={[6.717, 1.047, -4.212]}
              rotation={[-Math.PI / 2, 0, -1.833]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line079'
              castShadow
              receiveShadow
              geometry={nodes.Line079.geometry}
              material={materials['pelicula cinta']}
              position={[1.451, 1.047, -3.734]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.562, -0.562, -0.927]}
            />
            <mesh
              name='Line080'
              castShadow
              receiveShadow
              geometry={nodes.Line080.geometry}
              material={materials['pelicula cinta']}
              position={[-7.962, 1.047, 3.814]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line081'
              castShadow
              receiveShadow
              geometry={nodes.Line081.geometry}
              material={materials['pelicula cinta']}
              position={[-7.893, 1.047, 1.88]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line082'
              castShadow
              receiveShadow
              geometry={nodes.Line082.geometry}
              material={materials['pelicula cinta']}
              position={[7.198, 1.047, 0.02]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line083'
              castShadow
              receiveShadow
              geometry={nodes.Line083.geometry}
              material={materials['pelicula cinta']}
              position={[9.036, 1.047, -1.874]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line084'
              castShadow
              receiveShadow
              geometry={nodes.Line084.geometry}
              material={materials['pelicula cinta']}
              position={[-0.755, 1.047, -3.175]}
              rotation={[-Math.PI / 2, 0, 2.007]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line085'
              castShadow
              receiveShadow
              geometry={nodes.Line085.geometry}
              material={materials['pelicula cinta']}
              position={[-6.057, 1.047, -3.692]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line086'
              castShadow
              receiveShadow
              geometry={nodes.Line086.geometry}
              material={materials['pelicula cinta']}
              position={[-4.047, 1.047, -1.843]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line087'
              castShadow
              receiveShadow
              geometry={nodes.Line087.geometry}
              material={materials['pelicula cinta']}
              position={[-7.966, 1.047, -3.8]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line088'
              castShadow
              receiveShadow
              geometry={nodes.Line088.geometry}
              material={materials['pelicula cinta']}
              position={[-6.085, 1.047, 1.88]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line089'
              castShadow
              receiveShadow
              geometry={nodes.Line089.geometry}
              material={materials['pelicula cinta']}
              position={[-6.451, 1.047, -0.468]}
              rotation={[-Math.PI / 2, 0, -1.833]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line090'
              castShadow
              receiveShadow
              geometry={nodes.Line090.geometry}
              material={materials['pelicula cinta']}
              position={[-4.186, 1.047, 1.882]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.531, -0.531, -0.927]}
            />
            <mesh
              name='Line091'
              castShadow
              receiveShadow
              geometry={nodes.Line091.geometry}
              material={materials['pelicula cinta']}
              position={[-6.012, 1.047, 3.752]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line092'
              castShadow
              receiveShadow
              geometry={nodes.Line092.geometry}
              material={materials['pelicula cinta']}
              position={[3.332, 1.047, 0.021]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line093'
              castShadow
              receiveShadow
              geometry={nodes.Line093.geometry}
              material={materials['pelicula cinta']}
              position={[-2.286, 1.047, -0.06]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
            <mesh
              name='Line094'
              castShadow
              receiveShadow
              geometry={nodes.Line094.geometry}
              material={materials['pelicula cinta']}
              position={[5.192, 1.047, 0.045]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.55, -0.55, -0.927]}
            />
            <mesh
              name='Line095'
              castShadow
              receiveShadow
              geometry={nodes.Line095.geometry}
              material={materials['pelicula cinta']}
              position={[8.293, 1.047, 2.297]}
              rotation={[-Math.PI / 2, 0, 1.134]}
              scale={[-0.55, -0.55, -0.927]}
            />
            <mesh
              name='Line096'
              castShadow
              receiveShadow
              geometry={nodes.Line096.geometry}
              material={materials['pelicula cinta']}
              position={[2.943, 1.047, 1.358]}
              rotation={[-Math.PI / 2, 0, -1.833]}
              scale={[-0.582, -0.582, -0.927]}
            />
            <mesh
              name='Line097'
              castShadow
              receiveShadow
              geometry={nodes.Line097.geometry}
              material={materials['pelicula cinta']}
              position={[1.539, 1.047, 3.81]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.607, -0.607, -0.927]}
            />
            <mesh
              name='Line098'
              castShadow
              receiveShadow
              geometry={nodes.Line098.geometry}
              material={materials['pelicula cinta']}
              position={[-0.411, 1.047, 1.843]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={[-0.557, -0.557, -0.927]}
            />
          </group>
          <group
            name='CajaBase2'
            position={[-2.203, -3.608, 3.871]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={[1, 0.618, 0.848]}
          >
            <mesh
              name='Malla053'
              castShadow
              receiveShadow
              geometry={nodes.Malla053.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla053_1'
              castShadow
              receiveShadow
              geometry={nodes.Malla053_1.geometry}
              material={materials['papel antiguo-1']}
            />
          </group>
          <mesh
            name='CajaHuecos2'
            castShadow
            receiveShadow
            geometry={nodes.CajaHuecos2.geometry}
            material={materials['papel antiguo-1']}
            position={[1.037, -2.5, 5.713]}
            rotation={[Math.PI / 2, 0, -Math.PI / 3]}
            scale={[-0.815, -0.318, -1]}
          />
          <group
            name='CajaTapa2'
            position={[2.508, 0.827, -4.29]}
            rotation={[-2.648, 0.47, -0.239]}
            scale={[1, 0.618, 0.848]}
          >
            <mesh
              name='Malla052'
              castShadow
              receiveShadow
              geometry={nodes.Malla052.geometry}
              material={materials['cuero marron-1']}
            />
            <mesh
              name='Malla052_1'
              castShadow
              receiveShadow
              geometry={nodes.Malla052_1.geometry}
              material={materials[' cuadricula interior']}
            />
            <mesh
              name='Malla052_2'
              castShadow
              receiveShadow
              geometry={nodes.Malla052_2.geometry}
              material={materials['papel antiguo-1']}
            />
          </group>
        </group>
        <group name='maleta' position={[-0.049, 0.154, -0.002]} scale={0.025}>
          <group
            name='bisagra'
            position={[13.137, 3.28, -11.663]}
            scale={1.426}
          >
            <mesh
              name='Box018BoxBox021'
              castShadow
              receiveShadow
              geometry={nodes.Box018BoxBox021.geometry}
              material={materials['metal-2']}
              position={[0.051, 0.846, 0.049]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={-0.877}
            />
            <mesh
              name='ChamferCyl052'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl052.geometry}
              material={materials['metal-1']}
              position={[-0.48, 0.844, -0.079]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={[0.656, 0.659, 0.656]}
            />
            <mesh
              name='ChamferCyl053'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl053.geometry}
              material={materials['metal-1']}
              position={[0.48, -0.844, -0.079]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.656, 0.659, 0.656]}
            />
            <mesh
              name='Cylinder017'
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017.geometry}
              material={materials['metal-1']}
              position={[-0.348, -0.01, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[1.74, 1.244, 1.74]}
            />
          </group>
          <group
            name='bisagra001'
            position={[-13.166, 3.28, -11.663]}
            scale={1.426}
          >
            <mesh
              name='Box018BoxBox022'
              castShadow
              receiveShadow
              geometry={nodes.Box018BoxBox022.geometry}
              material={materials['metal-2']}
              position={[0.051, 0.846, 0.049]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={-0.877}
            />
            <mesh
              name='ChamferCyl054'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl054.geometry}
              material={materials['metal-1']}
              position={[-0.48, 0.844, -0.079]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
              scale={[0.656, 0.659, 0.656]}
            />
            <mesh
              name='ChamferCyl055'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl055.geometry}
              material={materials['metal-1']}
              position={[0.48, -0.844, -0.079]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.656, 0.659, 0.656]}
            />
            <mesh
              name='Cylinder018'
              castShadow
              receiveShadow
              geometry={nodes.Cylinder018.geometry}
              material={materials['metal-1']}
              position={[-0.348, -0.01, 0]}
              rotation={[Math.PI / 2, 0, Math.PI / 2]}
              scale={[1.74, 1.244, 1.74]}
            />
          </group>
          <group
            name='Group001'
            position={[21.352, 4.507, 9.918]}
            scale={1.426}
          >
            <mesh
              name='ChamferBox003'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox003.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl001'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl001.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl002'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl002.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl003'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl003.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group002'
            position={[21.352, 4.507, -10.455]}
            rotation={[0, 0, -Math.PI]}
            scale={-1.426}
          >
            <mesh
              name='ChamferBox004'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox004.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl005'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl005.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl006'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl006.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl007'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl007.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group003'
            position={[-21.352, 4.507, 9.918]}
            rotation={[Math.PI, 0, 0]}
            scale={-1.426}
          >
            <mesh
              name='ChamferBox005'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox005.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl008'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl008.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl009'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl009.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl010'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl010.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group004'
            position={[-21.352, 4.507, -10.455]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={1.426}
          >
            <mesh
              name='ChamferBox006'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox006.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl011'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl011.geometry}
              material={materials['metal-cuero-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl012'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl012.geometry}
              material={materials['metal-cuero-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl013'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl013.geometry}
              material={materials['metal-cuero-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group005'
            position={[21.352, -4.507, 9.918]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={-1.426}
          >
            <mesh
              name='ChamferBox007'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox007.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl024'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl024.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl025'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl025.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl026'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl026.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group006'
            position={[21.352, -4.507, -10.455]}
            rotation={[-Math.PI, 0, 0]}
            scale={1.426}
          >
            <mesh
              name='ChamferBox008'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox008.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl027'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl027.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl028'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl028.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl029'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl029.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group007'
            position={[-21.352, -4.507, 9.918]}
            rotation={[0, 0, -Math.PI]}
            scale={1.426}
          >
            <mesh
              name='ChamferBox009'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox009.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl030'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl030.geometry}
              material={materials['metal-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl031'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl031.geometry}
              material={materials['metal-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl032'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl032.geometry}
              material={materials['metal-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <group
            name='Group008'
            position={[-21.352, -4.507, -10.455]}
            scale={-1.426}
          >
            <mesh
              name='ChamferBox010'
              castShadow
              receiveShadow
              geometry={nodes.ChamferBox010.geometry}
              material={materials['metal-cuero-1']}
              position={[-11.814, -5.744, -5.457]}
              scale={[0.81, 0.845, 0.81]}
            />
            <mesh
              name='ChamferCyl033'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl033.geometry}
              material={materials['metal-cuero-1']}
              position={[-0.092, 0.031, 0.879]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl034'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl034.geometry}
              material={materials['metal-cuero-1']}
              position={[0.902, 0.031, -0.15]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1, 0.712, 1]}
            />
            <mesh
              name='ChamferCyl035'
              castShadow
              receiveShadow
              geometry={nodes.ChamferCyl035.geometry}
              material={materials['metal-cuero-1']}
              position={[-0.084, 0.874, -0.094]}
              rotation={[0, 1.571, 0]}
              scale={[1, 0.712, 1]}
            />
          </group>
          <mesh
            name='Box018BoxBox018'
            castShadow
            receiveShadow
            geometry={nodes.Box018BoxBox018.geometry}
            material={materials['metal-2']}
            position={[13.181, 4.517, 11.064]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1.005}
          />
          <mesh
            name='Box018BoxBox019'
            castShadow
            receiveShadow
            geometry={nodes.Box018BoxBox019.geometry}
            material={materials['metal-2']}
            position={[-13.167, 4.517, 11.064]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1.005}
          />
          <mesh
            name='Box018BoxBox020'
            castShadow
            receiveShadow
            geometry={nodes.Box018BoxBox020.geometry}
            material={materials['metal-2']}
            position={[0.393, 4.517, 11.064]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1.005}
          />
          <mesh
            name='Box22'
            castShadow
            receiveShadow
            geometry={nodes.Box22.geometry}
            material={materials['metal-2']}
            position={[0.158, 0.852, 10.86]}
            rotation={[Math.PI / 2, 0, -0.003]}
            scale={[0.561, 0.352, 0.561]}
          />
          <mesh
            name='Box23'
            castShadow
            receiveShadow
            geometry={nodes.Box23.geometry}
            material={materials.mango}
            position={[0.159, -1.93, 11.273]}
            rotation={[Math.PI / 2, 0, -0.006]}
            scale={[0.421, 0.606, 0.57]}
          />
          <group
            name='ChamferBox001'
            position={[0.002, -5.578, -0.277]}
            scale={1.426}
          >
            <mesh
              name='Malla108'
              castShadow
              receiveShadow
              geometry={nodes.Malla108.geometry}
              material={materials['cuero maleta-2']}
            />
            <mesh
              name='Malla108_1'
              castShadow
              receiveShadow
              geometry={nodes.Malla108_1.geometry}
              material={materials['cuero maleta-1']}
            />
          </group>
          <mesh
            name='ChamferCyl004'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl004.geometry}
            material={materials['metal-1']}
            position={[8.388, 4.335, 10.907]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.904, 0.902, 0.904]}
          />
          <mesh
            name='ChamferCyl015'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl015.geometry}
            material={materials['metal-3']}
            position={[13.79, 2.296, 11.211]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl016'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl016.geometry}
            material={materials['metal-3']}
            position={[13.79, 4.516, 11.126]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl019'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl019.geometry}
            material={materials['metal-1']}
            position={[-7.679, 4.335, 10.907]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.904, 0.902, 0.904]}
          />
          <mesh
            name='ChamferCyl020'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl020.geometry}
            material={materials['metal-3']}
            position={[-12.559, 2.296, 11.211]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl021'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl021.geometry}
            material={materials['metal-3']}
            position={[-12.559, 4.516, 11.123]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl022'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl022.geometry}
            material={materials['metal-3']}
            position={[0.143, 2.245, 11.211]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl023'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl023.geometry}
            material={materials['metal-3']}
            position={[1.002, 4.516, 11.211]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.752, 0.755, 0.752]}
          />
          <mesh
            name='ChamferCyl036'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl036.geometry}
            material={materials['metal-1']}
            position={[22.413, 4.335, 4.992]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.904, 0.902, 0.904]}
          />
          <mesh
            name='ChamferCyl037'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl037.geometry}
            material={materials['metal-1']}
            position={[22.413, 4.335, -0.593]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.904, 0.902, 0.904]}
          />
          <mesh
            name='ChamferCyl038'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl038.geometry}
            material={materials['metal-1']}
            position={[22.413, 4.335, -6.178]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.904, 0.902, 0.904]}
          />
          <mesh
            name='ChamferCyl039'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl039.geometry}
            material={materials['metal-1']}
            position={[-22.413, 4.335, 4.992]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.904, -0.902, -0.904]}
          />
          <mesh
            name='ChamferCyl040'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl040.geometry}
            material={materials['metal-1']}
            position={[-22.413, 4.335, -0.593]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.904, -0.902, -0.904]}
          />
          <mesh
            name='ChamferCyl041'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl041.geometry}
            material={materials['metal-1']}
            position={[-22.413, 4.335, -6.178]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.904, -0.902, -0.904]}
          />
          <mesh
            name='ChamferCyl046'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl046.geometry}
            material={materials['metal-cuero-1']}
            position={[22.539, 1.799, -10.652]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[-0.781, -0.349, -0.781]}
          />
          <mesh
            name='ChamferCyl049'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl049.geometry}
            material={materials['metal-cuero-1']}
            position={[-22.568, 1.799, 10.224]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[-0.781, -0.349, -0.781]}
          />
          <mesh
            name='ChamferCyl050'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl050.geometry}
            material={materials['metal-3']}
            position={[3.967, 1.499, 11.224]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.851, 0.627, 0.851]}
          />
          <mesh
            name='ChamferCyl051'
            castShadow
            receiveShadow
            geometry={nodes.ChamferCyl051.geometry}
            material={materials['metal-3']}
            position={[-3.613, 1.499, 11.224]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[-0.851, -0.627, -0.851]}
          />
          <mesh
            name='Cylinder13'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder13.geometry}
            material={materials['Material #39']}
            position={[-2.881, 0.557, 11.504]}
            rotation={[Math.PI / 2, 0, 1.567]}
            scale={[0.352, 0.561, 0.561]}
          />
          <mesh
            name='Cylinder14'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder14.geometry}
            material={materials['Material #39']}
            position={[3.671, 0.557, 11.482]}
            rotation={[Math.PI / 2, 0, 1.567]}
            scale={[0.352, 0.561, 0.561]}
          />
          <mesh
            name='Line002001'
            castShadow
            receiveShadow
            geometry={nodes.Line002001.geometry}
            material={materials['cuero maleta-2+']}
            position={[21.946, -5.025, -10.439]}
            scale={[1.426, 1.336, 1.426]}
          />
          <mesh
            name='Line003001'
            castShadow
            receiveShadow
            geometry={nodes.Line003001.geometry}
            material={materials['metal-2']}
            position={[13.211, 2.325, 11.029]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.06, 0.475, 1.06]}
          />
          <mesh
            name='Line004001'
            castShadow
            receiveShadow
            geometry={nodes.Line004001.geometry}
            material={materials['metal-2']}
            position={[-13.137, 2.325, 11.029]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.06, 0.475, 1.06]}
          />
          <mesh
            name='Line005001'
            castShadow
            receiveShadow
            geometry={nodes.Line005001.geometry}
            material={materials['metal-2']}
            position={[0.423, 2.55, 11.029]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.06, 0.475, 1.06]}
          />
          <mesh
            name='Line006001'
            castShadow
            receiveShadow
            geometry={nodes.Line006001.geometry}
            material={materials['metal-2']}
            position={[3.97, 0.846, 11.034]}
            rotation={[Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.409, 0.463, 1.409]}
          />
          <mesh
            name='Line007001'
            castShadow
            receiveShadow
            geometry={nodes.Line007001.geometry}
            material={materials['metal-2']}
            position={[-3.611, 0.846, 11.034]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[-1.409, -0.463, -1.409]}
          />
          <mesh
            name='Rectangle001'
            castShadow
            receiveShadow
            geometry={nodes.Rectangle001.geometry}
            material={materials['metal-3']}
            position={[0.031, 3.172, -0.262]}
            scale={[1.428, 1.412, 1.428]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Caja-mexicana-maleta-01.glb')
