/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/sensorama-sin-texturas-01.glb --shadows 
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./public/sensorama-sin-texturas-01.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.381, 0.022, -1.667]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.023, 0.021, 0.023]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Malla.geometry}
          material={materials['color blanco']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Malla_1.geometry}
          material={materials['color gris']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./public/sensorama-sin-texturas-01.glb')
